name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2

    - name: Set environment variables
      id: vars
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Dependency packages (apt)
      run: |
        sudo apt update
        sudo apt -y install git gcc-arm-none-eabi python3-pip srecord stm32flash zip unzip wget

    - name: Dependency packages (pip)
      run: python3 -m pip install --user crcmod intelhex

    - name: Build dist
      run: |
        export VER=${{ steps.vars.outputs.sha_short }}
        make -j4 dist VER=$VER
        mkdir -p _cidist
        mv out/flashfloppy-$VER .
        rm flashfloppy-$VER/RELEASE_NOTES
        git rev-parse HEAD >flashfloppy-$VER/COMMIT
        zip -r flashfloppy-$VER.zip flashfloppy-$VER
        mv flashfloppy-$VER.zip _cidist/

    - name: Build debug dist
      run: |
        export VER=${{ steps.vars.outputs.sha_short }}-debug
        make -j4 dist VER=$VER level=debug
        mv out/flashfloppy-$VER .
        rm flashfloppy-$VER/RELEASE_NOTES
        git rev-parse HEAD >flashfloppy-$VER/COMMIT
        echo debug >>flashfloppy-$VER/COMMIT
        zip -r flashfloppy-$VER.zip flashfloppy-$VER
        mv flashfloppy-$VER.zip _cidist/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: FlashFloppy.CI.${{ steps.vars.outputs.sha_short }}
        path: _cidist
